ws_host: 0.0.0.0
ws_port: 9293
log: log/app.log
pid: tmp/pids/app.pid
img_path: front/static/img/
BLOCKS_IN_MAP_DIM: 5
BLOCK_DIM: 10
GREEN_ORB_PER_BLOCK: 1
BLACK_ORB_LIMIT: 0
BLACK_ORB_START_SPEED: 60
BLACK_ORB_MAX_SPEED: 60
BLACK_ORB_START_HP: 1000
BLACK_ORB_START_ATTACK: 100
BLACK_ORB_START_DEFENCE: 10
:start_unit_type: :swordsman
:base_unit_limit: 1
:unit_limit_per_town: 1
:start_res:
  :gold: 10
  :wood: 7
  :settlers: 1
:max_random_res:
  :gold: 10
  :wood: 5
  :stone: 3
:random_res_town_radius: 7
:res_spawner_tick: 60
:resource_lifetime_in_the_wild: 86400
:max_town_aid: 20
:orb_tick: 3
:spawn_elf_every: 3600
:spawn_elves: true
:max_life: 15
:elf_login: Elves
:dummy_login: dummy
:unit_class:
  :swordsman: Swordsman
  :hero_swordsman: HeroSwordsman
  :elf_swordsman: ElfSwordsman
:buildings:
  :barracs:
    :units:
      - :swordsman
    :max_level: 10
    :cost:
      :formula:
        1:
          :time: 60
          :res:
            :gold: 10
            :wood: 2
        2:
          :time: + 60
          :res:
            :gold: + 10
            :wood: + 2
  :tavern:
    :units:
      - :hero_swordsman
    :max_level: 1
    :cost:
      :formula:
        1:
          :time: 60
          :res:
            :gold: 10
            :wood: 10
  :roads:
    :max_level: 10
    :cost:
      :formula:
        1:
          :time: 4
          :res:
            :gold: 5
            :wood: 2
        2:
          :time: + 2
          :res:
            :gold: + 1
            :wood: + 1
  :factory:
    :resource: :gold
    :max_level: 10
    :cost:
      :formula:
        1:
          :time: 4
          :res:
            :gold: 5
            :wood: 2
        2:
          :time: 20
          :res:
            :gold: 10
            :wood: 4
  :sawmill:
    :resource: :wood
    :max_level: 10
    :cost:
      :formula:
        1:
          :time: 4
          :res:
            :gold: 5
            :wood: 2
        2:
          :time: + 10
          :res:
            :gold: + 10
            :wood: + 4
            :stone: + 2
  :quarry:
    :resource: :stone
    :max_level: 10
    :cost:
      :formula:
        1:
          :time: 4
          :res:
            :gold: 5
            :wood: 2
        2:
          :time: 20
          :res:
            :gold: + 10
            :wood: + 4
  :farm:
    :max_level: 10
    :cost:
      :formula:
        1:
          :time: 4
          :res:
            :gold: 5
            :wood: 2
        2:
          :time: + 10
          :res:
            :gold: + 10
            :wood: + 4
        5:
          :time: + 60
          :res:
            :gold: + 20
            :wood: + 8
            :stone: + 2
:swordsman:
  :required_buildings:
    - :barracs
  :ap: 20
  :attack: 5
  :defence: 5
  :initiative: 1
  :cost_res:
    :gold: 10
    :wood: 1
:hero_swordsman:
  :required_buildings:
    - :tavern
    - :barracs
  :ap: 30
  :attack: 4
  :defence: 4
  :initiative: 2
  :cost_res:
    :gold: 100
    :wood: 10
:elf_swordsman:
  :ap: 0
  :attack: 1
  :defence: 1
  :initiative: 3
  :cost_res:
    :gold: 0
:town:
  :ap: 0
  :attack: 1
  :defence: 1
  :initiative: 0
  :radius: 3
:resource:
  :gold:
    :production_building: :factory
    :production_time: 1
    :delivery_time: 0
    :profession: Peon
  :wood:
    :production_building: :sawmill
    :production_time: 3
    :delivery_time: 1
    :profession: Woodcutter
  :stone:
    :production_building: :quarry
    :production_time: 5
    :delivery_time: 2
    :profession: Stonecutter
:terrain_move_cost:
  :grass: 1
  :tree: 2
  :mountain: 3
:terrain_to_res:
  :grass: :gold
  :tree: :wood
  :mountain: :stone
