ws_host: 0.0.0.0
ws_port: 9293
log: log/app.log
pid: tmp/pids/app.pid
BLOCKS_IN_MAP_DIM: 5
BLOCK_DIM: 10
GREEN_ORB_PER_BLOCK: 1
BLACK_ORB_LIMIT: 0
BLACK_ORB_START_SPEED: 60
BLACK_ORB_MAX_SPEED: 60
BLACK_ORB_START_HP: 1000
BLACK_ORB_START_ATTACK: 100
BLACK_ORB_START_DEFENCE: 10
img_path: front/static/img/
START_GLORY: 120
START_MAX_GLORY: 200
START_UNIT_TYPE: swordsman
start_res:
  gold: 10
  wood: 7
  settlers: 1
max_random_res: 10
random_res_town_radius: 7
res_spawner_tick: 3600
resource_lifetime_in_the_wild: 86400
max_town_aid: 20
orb_tick: 3
MAX_LIFE: 15
DUMMY_LOGIN: dummy
unit_class:
  swordsman: Swordsman
  hero_swordsman: HeroSwordsman
buildings:
  barracs:
    units:
      - swordsman
    max_level: 10
    cost:
      formula:
        1:
          time: 60
          res:
            gold: 10
            wood: 2
        2:
          time: + 60
          res:
            gold: + 10
            wood: + 2
  tavern:
    units:
      - hero_swordsman
    max_level: 1
    cost:
      formula:
        1:
          time: 60
          res:
            gold: 10
            wood: 10
  roads:
    max_level: 10
    cost:
      formula:
        1:
          time: 4
          res:
            gold: 5
            wood: 2
        2:
          time: + 2
          res:
            gold: + 1
            wood: + 1
  factory:
    resource: gold
    max_level: 10
    cost:
      formula:
        1:
          time: 4
          res:
            gold: 5
            wood: 2
        2:
          time: 20
          res:
            gold: 10
            wood: 4
  sawmill:
    resource: wood
    max_level: 10
    cost:
      formula:
        1:
          time: 4
          res:
            gold: 5
            wood: 2
        2:
          time: + 10
          res:
            gold: + 10
            wood: + 4
            stone: + 2
  quarry:
    resource: stone
    max_level: 10
    cost:
      formula:
        1:
          time: 4
          res:
            gold: 5
            wood: 2
        2:
          time: 20
          res:
            gold: + 10
            wood: + 4
swordsman:
  required_buildings:
    - barracs
  ap: 20
  attack: 3
  defence: 3
  initiative: 1
  cost_res:
    gold: 10
    wood: 1
  cost_glory: 10
hero_swordsman:
  required_buildings:
    - tavern
    - barracs
  ap: 30
  attack: 4
  defence: 4
  initiative: 2
  cost_res:
    gold: 100
    wood: 10
  cost_glory: 20
town:
  ap: 0
  attack: 1
  defence: 1
  initiative: 0
  radius: 3
resource:
  gold:
    production_building: factory
    production_time: 1
    delivery_time: 0
    profession: Peon
  wood:
    production_building: sawmill
    production_time: 3
    delivery_time: 1
    profession: Woodcutter
  stone:
    production_building: quarry
    production_time: 5
    delivery_time: 2
    profession: Stonecutter
terrain_move_cost:
  grass: 1
  tree: 2
  mountain: 3
terrain_to_res:
  grass: gold
  tree: wood
  mountain: stone
