BLOCKS_IN_MAP_DIM: 3
:res_spawner_tick: 10
:spawn_elf_every: 60
:spawn_elves: true
:buildings:
  :barracs:
    :cost:
      :formula:
        1:
          :time: 10
        2:
          :time: 20
  :tavern:
    :cost:
      :formula:
        1:
          :time: 5
