BLOCKS_IN_MAP_DIM: 1
:res_spawner_tick: 10
:buildings:
  :barracs:
    :cost:
      :formula:
        1:
          :time: 10
        2:
          :time: 20
  :tavern:
    :cost:
      :formula:
        1:
          :time: 5
