BLOCKS_IN_MAP_DIM: 1
res_spawner_tick: 60
resource_lifetime_in_the_wild: 60
buildings:
  barracs:
    cost:
      formula:
        1:
          time: 10
        2:
          time: 20
  tavern:
    cost:
      formula:
        1:
          time: 5
