BLOCKS_IN_MAP_DIM: 1
buildings:
  barracs:
    cost:
      formula:
        1:
          time: 1
        2:
          time: 60
  tavern:
    max_level: 2
    cost:
      formula:
        1:
          time: 1
