host: 0.0.0.0
port: 9293
log: /home/user/public_html/waroforbs/log/app.log
pid: tmp/pids/app.pid
BLOCKS_IN_MAP_DIM: 5
GREEN_ORB_PER_BLOCK: 3
BLACK_ORB_START_SPEED: 5
BLACK_ORB_MAX_SPEED: 3
BLACK_ORB_START_HP: 1000
BLACK_ORB_START_DAMAGE: 100
BLACK_ORB_START_DEFENCE: 10
