ws_host: 0.0.0.0
ws_port: 9293
log: log/app.log
pid: tmp/pids/app.pid
BLOCKS_IN_MAP_DIM: 1
BLOCK_DIM: 10
GREEN_ORB_PER_BLOCK: 1
BLACK_ORB_LIMIT: 0
BLACK_ORB_START_SPEED: 60
BLACK_ORB_MAX_SPEED: 60
BLACK_ORB_START_HP: 1000
BLACK_ORB_START_ATTACK: 100
BLACK_ORB_START_DEFENCE: 10
img_path: front/static/img/
START_GLORY: 120
START_MAX_GLORY: 200
START_UNIT_TYPE: swordsman
MAX_LIFE: 15
DUMMY_LOGIN: dummy
barracs:
  unit: swordsman
  cost_time: 6
  cost_res:
    gold: 20
    wood: 5
swordsman:
  ap: 20
  attack: 3
  defence: 3
  initiative: 1
  cost_res:
    gold: 10
  cost_glory: 10
town:
  ap: 0
  attack: 1
  defence: 1
  initiative: 0
unit_class:
  swordsman: Swordsman
resource:
  gold:
    time_to_collect: 1
    profession: Peon
  wood:
    time_to_collect: 3
    profession: Woodcutter
  stone:
    time_to_collect: 5
    profession: Stonecutter
