ws_host: 0.0.0.0
ws_port: 9293
log: log/app.log
pid: tmp/pids/app.pid
BLOCKS_IN_MAP_DIM: 1
GREEN_ORB_PER_BLOCK: 1
BLACK_ORB_LIMIT: 0
BLACK_ORB_START_SPEED: 60
BLACK_ORB_MAX_SPEED: 60
BLACK_ORB_START_HP: 1000
BLACK_ORB_START_DAMAGE: 100
BLACK_ORB_START_DEFENCE: 10
img_path: front/static/img/
HEAVY_INFANTRY_LIMIT: 10
barracs:
  cost_time: 60
  cost_res:
    gold: 20
    wood: 5
